cmake_minimum_required(VERSION 3.20)
include("${CMAKE_CURRENT_LIST_DIR}/log.cmake")

function(require_tool TOOL_VALUE)
    if("${TOOL_VALUE}" STREQUAL "")
        cl_log_error("missing tool name")
    endif()

    if(IS_ABSOLUTE "${TOOL_VALUE}")
        if(NOT EXISTS "${TOOL_VALUE}")
            cl_log_error("missing tool: ${TOOL_VALUE}")
        endif()
        return()
    endif()

    find_program(_tool_path NAMES "${TOOL_VALUE}")
    if(NOT _tool_path)
        cl_log_error("missing tool: ${TOOL_VALUE}")
    endif()
endfunction()

function(resolve_tool_with_fallback VAR_NAME)
    set(_fallbacks ${ARGN})
    set(_requested "${${VAR_NAME}}")

    if("${_requested}" STREQUAL "")
        cl_log_error("missing tool name")
    endif()

    if(IS_ABSOLUTE "${_requested}")
        if(NOT EXISTS "${_requested}")
            cl_log_error("missing tool: ${_requested}")
        endif()
        set(_resolved "${_requested}")
    else()
        find_program(_requested_path NAMES "${_requested}")
        if(_requested_path)
            set(_resolved "${_requested}")
        else()
            set(_resolved "")
            foreach(_cand IN LISTS _fallbacks)
                find_program(_cand_path NAMES "${_cand}")
                if(_cand_path)
                    cl_log_warn("${VAR_NAME} '${_requested}' not found; fallback to '${_cand}'")
                    set(_resolved "${_cand}")
                    break()
                endif()
            endforeach()
            if("${_resolved}" STREQUAL "")
                cl_log_error("missing tool: ${_requested}")
            endif()
        endif()
    endif()

    set(${VAR_NAME} "${_resolved}" PARENT_SCOPE)
endfunction()

cl_log_step("checking host tools")

require_tool("${GIT_TOOL}")
require_tool("${TAR_TOOL}")
require_tool("${XORRISO_TOOL}")
require_tool("${CC_TOOL}")
require_tool("${KERNEL_CXX_TOOL}")
require_tool("${LD_TOOL}")
require_tool("${OBJCOPY_TOOL}")
require_tool("${OBJDUMP_TOOL}")
require_tool("${READELF_TOOL}")
require_tool("${NM_TOOL}")
require_tool("${ADDR2LINE_TOOL}")
require_tool("${USER_CC_TOOL}")
require_tool("${USER_LD_TOOL}")
require_tool("${RUSTC_TOOL}")
require_tool("${MAKE_TOOL}")
require_tool("${SH_TOOL}")

cl_log_info("required tools are available")
